### ISSUE TITLE
CSS file not built when using multiple Webpack entrypoints

### ISSUE THREAD

**Issue by steveluscher** [js-next/react-style-webpack-plugin#11]
Our app makes use of Webpack's multiple-entry-points-with-chunk-loader feature. I'm having a hard time getting react-style-webpack-loader to build a CSS bundle under these conditions.

Take `./examples/0.13/webpack/` for… example:

```javascript
entry: './index.js',
output: {
  filename: "bundle.js",
  path: __dirname + "/build"
},
```

…works as intended, but if I change it to:

```javascript
entry: {index: './index.js'},
output: {
  filename: "[name].js",
  path: __dirname + "/build"
},
```

…it builds only `index.js` and `index.js.map`, but no CSS files.

**Comment by SanderSpies** [comment]
Did you provide `index` to `ReactStylePlugin` inside webpack.config.js's plugins? 

See https://github.com/js-next/react-style/blob/master/examples/0.12/react-router/webpack.config.js for example.

**Comment by steveluscher** [comment]
There it is. Thanks Sander!
